SELECT YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER,COUNT(DISTINCT ONLINE_SALE.USER_ID) as USERS
FROM ONLINE_SALE
JOIN USER_INFO ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), 
		MONTH(SALES_DATE), 
        GENDER
ORDER BY YEAR(SALES_DATE), 
		MONTH(SALES_DATE), 
        GENDER