SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
        PRODUCT_ID,
        USER_ID,
        SALES_AMOUNT
FROM ONLINE_SALE AS N
WHERE DATE_FORMAT(SALES_DATE, "%m") = 03
UNION
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
        PRODUCT_ID,
        NULL,
        SALES_AMOUNT
FROM OFFLINE_SALE AS OFF
WHERE DATE_FORMAT(SALES_DATE, "%m") = 03
ORDER BY SALES_DATE,PRODUCT_ID, USER_ID