-- 코드를 입력하세요
SET @ALL_U = (SELECT COUNT(*) FROM USER_INFO WHERE JOINED BETWEEN '20210101' and '20211231');

SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH
    ,COUNT(DISTINCT S.USER_ID) PUCHASED_USERS
    ,ROUND(COUNT(DISTINCT S.USER_ID) / @ALL_U ,1) PUCHASED_RATIO
FROM (SELECT * FROM USER_INFO WHERE JOINED BETWEEN '20210101' and '20211231') U
    -- LEFT OUTER 
    JOIN ONLINE_SALE S
    ON U.USER_ID = S.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH