-- 코드를 입력하세요
SELECT WRITER_ID,NICKNAME,TOTAL_SALES
FROM 
(SELECT B.WRITER_ID, U.NICKNAME, SUM(PRICE) TOTAL_SALES
FROM (SELECT * FROM USED_GOODS_BOARD WHERE STATUS = 'DONE') B
    INNER JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
GROUP BY WRITER_ID) C
WHERE TOTAL_SALES >= '700000'
ORDER BY TOTAL_SALES ASC