-- 코드를 입력하세요
# SELECT
#     M.MEMBER_NAME,
#     R.REVIEW_TEXT,
#     DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") REVIEW_DATE
# FROM MEMBER_PROFILE M, REST_REVIEW R
# WHERE M.MEMBER_ID = R.MEMBER_ID and 
# M.MEMBER_ID = 
# (SELECT MEMBER_ID FROM REST_REVIEW
# GROUP BY MEMBER_ID
# ORDER BY COUNT(*) DESC LIMIT 1)
# ORDER BY REVIEW_DATE, REVIEW_TEXT;

# SELECT MEMBER_ID,count(*) FROM REST_REVIEW
# GROUP BY MEMBER_ID
# ORDER BY COUNT(*) DESC



set @MAXNUM = (select COUNT(*) CNT FROM REST_REVIEW
                GROUP BY MEMBER_ID
                ORDER BY CNT DESC LIMIT 1);
                
SELECT MEMBER_NAME, REVIEW_TEXT, 
    DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") REVIEW_DATE 
FROM
(SELECT R.MEMBER_ID, R.REVIEW_TEXT, R.REVIEW_DATE FROM REST_REVIEW R
    INNER JOIN
        (select MEMBER_ID, COUNT(*) CNT FROM REST_REVIEW
        GROUP BY MEMBER_ID
        HAVING COUNT(*) = @MAXNUM) MAX_ID
    ON R.MEMBER_ID = MAX_ID.MEMBER_ID) S
LEFT OUTER JOIN MEMBER_PROFILE P
ON P.MEMBER_ID = S.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC